# WARNING: This file was copied from kube-core operator just to unblock deploying the new control-plane.
#          We **must** find an owner for this component and remove this file from this repository.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: pod-checkpointer
    tectonic-operators.coreos.com/managed-by: kube-core-operator
    tier: control-plane
  name: pod-checkpointer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      tier: control-plane
      k8s-app: pod-checkpointer
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        checkpointer.alpha.coreos.com/checkpoint: "true"
      labels:
        k8s-app: pod-checkpointer
        tier: control-plane
    spec:
      containers:
      - command:
        - /checkpoint
        - --lock-file=/var/run/lock/pod-checkpointer.lock
        - --kubeconfig=/etc/checkpointer/kubeconfig
        - --checkpoint-grace-period=5m
        - --container-runtime-endpoint=unix:///var/run/crio/crio.sock
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/coreos/pod-checkpointer:9dc83e1ab3bc36ca25c9f7c18ddef1b91d4a0558
        imagePullPolicy: Always
        name: pod-checkpointer
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/checkpointer
          name: kubeconfig
        - mountPath: /etc/kubernetes
          name: etc-kubernetes
        - mountPath: /var/run
          name: var-run
      serviceAccountName: pod-checkpointer
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - name: kubeconfig
        secret:
          secretName: controller-manager-kubeconfig
      - hostPath:
          path: /etc/kubernetes
        name: etc-kubernetes
      - hostPath:
          path: /var/run
        name: var-run
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
