# WARNING: This file was copied from kube-core operator just to unblock deploying the new control-plane.
#          We **must** find an owner for this component and remove this file from this repository.
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-proxy
    tectonic-operators.coreos.com/managed-by: kube-core-operator
    tier: node
  name: kube-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy
      tier: node
  template:
    metadata:
      labels:
        k8s-app: kube-proxy
        tier: node
    spec:
      containers:
      - command:
        - ./hyperkube
        - proxy
        - --cluster-cidr=10.3.0.0/16
        - --hostname-override=$(NODE_NAME)
        - --kubeconfig=/etc/kubernetes/kubeconfig
        - --proxy-mode=iptables
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: quay.io/coreos/hyperkube:v1.9.3_coreos.0
        name: kube-proxy
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
          readOnly: true
        - mountPath: /etc/kubernetes
          name: kubeconfig
          readOnly: true
      hostNetwork: true
      serviceAccountName: kube-proxy
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /etc/ssl/certs
        name: ssl-certs-host
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: controller-manager-kubeconfig
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
