FROM registry.svc.ci.openshift.org/openshift/origin-release:v4.0 as origin-release

FROM fedora:29 as jq
RUN yum install -y jq
COPY --from=origin-release release-manifests/image-references .
RUN jq '.spec.tags |= map(.name as $name | if ([IMAGES] | index($name)) then .from.name |= "docker.io/DOCKER_ORG/origin-"+$name+":latest" else . end)' image-references > image-references-updated

FROM registry.svc.ci.openshift.org/openshift/origin-release:v4.0
COPY --from=jq image-references-updated release-manifests/image-references
